### ISSUE TITLE
Make error with current release of LAStools.zip

### ISSUE THREAD

**Issue by bengarrett33** [LAStools/LAStools.github.io#1]
I am getting an error when trying to build the tool from the latest LAStools.zip release.

Dockerfile
```
FROM python:3.7 as base

RUN apt-get install -y \
    unzip \
    wget


RUN cd /usr/local/src/ && \
    wget https://lastools.github.io/download/LAStools.zip && \
    unzip LAStools.zip && \
    cd LAStools && \
    make

ENTRYPOINT [ "bin/bash" ]
```

```
docker build -t las_container -f Dockerfile .
```

Results in 

```
#0 4.350 cd LASlib && make
#0 4.353 make[1]: Entering directory '/usr/local/src/LAStools/LASlib'
#0 4.353 cd src && make
#0 4.356 make[2]: Entering directory '/usr/local/src/LAStools/LASlib/src'
#0 4.357 /bin/sh: 1: cd: can't cd to /home/jochen/srd
#0 4.357 make[2]: *** [Makefile:155: all] Error 2
#0 4.357 make[2]: Leaving directory '/usr/local/src/LAStools/LASlib/src'
#0 4.358 make[1]: *** [Makefile:2: all] Error 2
#0 4.358 make[1]: Leaving directory '/usr/local/src/LAStools/LASlib'
#0 4.358 make: *** [Makefile:2: all] Error 2
```

Building locally on my mac results in the same. Seems to be some sort of an accidental inclusion of a user's name (jochen) in a path in the build steps. Running the same build works when using the second most recent zip (`LAStools_210720.zip`)

**Comment by rapidlasso** [comment]
Thanks for the hint, the redundand file was out of date: It is fixed now.
For own builds/sourcecode: Best use original download at https://github.com/LAStools/LAStools
For binaries: Best use original download at https://rapidlasso.de
